#+title: Yash Honda PDF (=yhpdf=) Manual
#+latex_class_options: [9pt]
#+latex_header: \setminted{breaklines=true, style=default}
#+latex_header: \usepackage{parskip}
#+latex_class: org-report
#+latex_class_options: [9pt]
#+latex_header:\usepackage{sectsty}
#+latex_header:\sectionfont{\fontsize{12}{15}\selectfont}
#+latex_header:\subsectionfont{\fontsize{11}{11}\selectfont}
#+latex_header: \setlength\parindent{0pt}
#+latex_header: \usepackage{parskip}
#+latex_header: \usepackage{pifont}
#+latex_header: \makeatletter
#+latex_header: \def\@makechapterhead#1{%
#+latex_header:  {\parindent \z@ \raggedright \normalfont
#+latex_header:    \ifnum \c@secnumdepth >\m@ne
#+latex_header:        \LARGE\bfseries \thechapter:
#+latex_header:    \fi
#+latex_header:    \interlinepenalty\@M
#+latex_header:    \LARGE \bfseries #1\par\nobreak
#+latex_header:    \vskip 10\p@
#+latex_header:  }}
#+latex_header:\def\@makeschapterhead#1{%
#+latex_header:  {\parindent \z@ \raggedright
#+latex_header:    \normalfont
#+latex_header:    \interlinepenalty\@M
#+latex_header:    \Huge \bfseries  #1\par\nobreak
#+latex_header:    \vskip 10\p@
#+latex_header:  }}
#+latex_header:\makeatother

#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Installation

** Basic
   Use MS Windows 10.

   1. Install *Ghostscript (64-bit)*:
      A. Go to _[[https://ghostscript.com/releases/gsdnld.html]]_.
      B. Download the file *Ghostscript for Windows (64 bit)* with
         the AGPL license. _Do not use the 32 bit
         version, it is incompatible with =yhpdf=._
      C. Run the installer with the standard steps, and click =Finish=
         once done. It should launch a website, telling you Ghostscript
         is installed.
   2. Get *yhpdf*:
      A. Download =yhpdf.exe= from
         _https://github.com/nebhrajani-a/yhpdf/releases/download/v1.4/yhpdf.exe_.
         Your browser may call it "Dangerous" since it's not a
         Microsoft-verified program. Click the arrow for options and
         select "Keep".
      B. Copy =yhpdf= from your =Downloads= folder and paste it in
         =C:\Program Files= (This PC $\rightarrow$ Local Disk
         $\rightarrow$ Program Files).
      C. Double click on =yhpdf=.
         A. If "Windows protected your PC" launches, click "More
            info", then select "Run anyway" on the bottom right.
            Windows will remember your preference.
         B. _Wait for 20 seconds_. If it doesn't
            launch, double click again, and wait for 10 more seconds. On
            old machines, =yhpdf= takes time to start up. Be patient, it
            runs much faster than it starts.
      D. Once it starts, you should see a window with four buttons and
         some text. Go down to the taskbar, right click on =yhpdf='s
         feather icon, and select "Pin to taskbar".
      E. =yhpdf= is now ready for use.
      F. If =yhpdf= doesn't start and reports an error, make sure
         Ghostscript is installed. If there's some other error you
         can't resolve, report it to the package maintainer.

** Advanced

   On any platform, install Python 3 and Ghostscript 64-bit. Then,
   =pip3 install pypdf2 ghostscript=. Run with =python3 yhpdf.py=.

* Usage

  Usage is intuitive:

  1. Click "Select a file" to upload the PDF you want to split and
     compress.
     1. A popup will tell you which file has been selected.
        Click "OK".
  2. Click "Select output folder" to select the folder into which the
     new PDFs will be put.
     1. A popup will tell you which folder has been selected. Click
        "OK".
  3. Click "Process PDF" to process the PDF. This can take up to 60
     seconds, depending on the speed of your machine and the size of
     the input PDF.
     1. _Do not close =yhpdf= even if Windows says "Not Responding"_.
        Killing =yhpdf= may damage the output. Wait for it to
        complete.
     2. Once the PDF process is complete, a popup will ask you if you
        want to view the output files. Click "Yes".
  4. Repeat steps 1 to 3 for as many PDFs as required.
  5. Click "Exit" when you're done.


* Technical Description
** What?
   =yhpdf= is a GUI tool which:
   - Takes an input PDF file.
   - Splits it into one PDF file per page.
   - Compresses each page PDF to less than 195KB.

   Given the intended use-case, the only platform with first-class
   support is MS Windows 10 (compiled binary provided). None of the
   Python is OS-specific though, and the CI tests run on Ubuntu.

** How?
   =yhpdf= uses PyPDF2 to split the PDF page-wise, then uses
   Ghostscript's compression on each of these pages. If the file size
   is greater than 195KB, it first tries =-dPDFSETTINGS=/ebook=. If
   the file size is still greater than 195KB, it tries
   =-dPDFSETTINGS=/screen=. This gets most scanned pages below 200KB.
   If this fails, it raises an error. In essence, =yhpdf= is just a
   =for= loop which generates per-page PDFs then compresses them.

   The GUI uses Tkinter and is cross-platform. If you're proficient in
   Python, you can probably get =yhpdf.py= running in your own
   environment.

** Known Issues
   The biggest user-facing issue is the slow startup time. This is
   unfortunately out of =yhpdf='s control, since =pyinstaller= in
   single file mode needs to decompress the (single) =.exe= file to
   run, which takes time, especially on Windows because of virus
   scanning.

   If this bothers you, either keep it running all the time by
   auto-starting it (it uses next to no RAM and CPU while idling), or
   get Python and run it from the command line.

* =yhpdf.py= Source
https://github.com/nebhrajani-a/yhpdf
